A_REQUEST_DECIDE_MATCHING: str = "A_REQUEST_DECIDE_MATCHING"
A_MATCHING_CANCELED_BY_DEACTIVATION: str = "A_MATCHING_CANCELED_BY_DEACTIVATION"
MAN_PROPOSAL_DEACTIVATED: str = "MAN_PROPOSAL_DEACTIVATED"
WOMAN_PROPOSAL_DEACTIVATED: str = "WOMAN_PROPOSAL_DEACTIVATED"
